### ISSUE TITLE
Total week time calculation is wrong

### ISSUE THREAD

**Issue by pde-bakk** [FreekBes/codam_intra_monit_system_display#3]
On sundays only, the "monitoring system progress" also counts last weeks Sunday as part of the current week.

**Comment by FreekBes** [comment]
On 1.0.1 (currently the latest version), I'm unable to replicate this behavior in the logtimes chart.
![image](https://user-images.githubusercontent.com/36384333/142779275-62feaec5-5d46-4531-96d5-0564d5383b17.png)
![image](https://user-images.githubusercontent.com/36384333/142779276-3e087149-18df-4064-912e-920456ac46be.png)

**Comment by FreekBes** [comment]
Ah, I see what you mean. The calculation for the percentage in the banner on top of profiles is wrong. Writing a fix now.
